### ISSUE TITLE
Stop after n seconds?

### ISSUE THREAD

**Issue by shevegen** [loktar00/JQuery-Snowfall#39]
Hi,

Would it be possible to add an API to stop the snowfall after n seconds?

I'd like to show them for e. g. 5 seconds but then stop, ideally with a fade out event but more importantly so just to have it stop after n seconds.

**Comment by TimSmith714** [comment]
Could you use SetInterval with $('#element').snowfall('clear'); ?
`var stopSnow = window.setInterval($('#element').snowfall('clear'), 500);`
Have to admit I haven't tried but this is what I've done on a few occaisions.

**Comment by loktar00** [comment]
:+1: What @TimSmith714 is the course I would take, I would probably use a setTimeout like so

```setTimeout(function(){
                                        $('#element').snowfall('clear');
                       }, 5000);```

**Comment by TimSmith714** [comment]
Of course, much better. Kicking myself now :-)
