### ISSUE TITLE
Collect doesn't seem to be working

### ISSUE THREAD

**Issue by dylanh724** [loktar00/JQuery-Snowfall#45]
Hi --

I am using this and snowfall is working great:

$(document).snowfall({collection : '.note'});

However, the collection doesn't seem to work. I've confirmed that .note exists and caps is correct.

Is there something I'm doing wrong? Love this code btw

EDIT: I tried adding an ID, and adding by ID '#note' didn't work. Snow works, but not collection :/

**Comment by dylanh724** [comment]
was there an update recently? Seems to be working now, with this example:
`$(document).ready(function() {
    $(document).snowfall({collection : '.nav-menu-cont'});
});`

**Comment by loktar00** [comment]
Hmm not sure of one in particular, but glad it works :+1:

**Comment by SasSam** [comment]
It doesn't work for me. Canvas has been created above the container, but it's not catching the flakes.
