### ISSUE TITLE
Without jQuery Version

### ISSUE THREAD

**Issue by muratcesmecioglu** [loktar00/JQuery-Snowfall#55]
Hello. First of all, thank you for this plugin. I've been using since 2014 on my blog. But now i redesign my theme and i don't want to use big jquery core just for this plugin. As a javascript noob, i purified this plugin from jquery but i removed some features. Like shadow or device orientation. I am hoping this will be a guide to who want to use without jquery.
It will be allways round, no shadow, no image. It based on Version 1.51 Dec 2nd 2012.

https://github.com/muratcesmecioglu/LetItSnow.JS

**Comment by loktar00** [comment]
Hey @muratcesmecioglu  Nice job on the script. I actually made a purejs version years ago that is included with this ( I haven't looked in so long) but it's pretty much feature parity with the JQ version.

Indexpure.html in the examples directory uses it and shows how to instantiate it, etc.

https://github.com/loktar00/JQuery-Snowfall/blob/master/examples/indexpure.html

**Comment by muratcesmecioglu** [comment]
All these years and i missed it :) But it was very educational for me.
